### ISSUE TITLE
Please help to reset BOLD formatting for xTerm colors in bash script

### ISSUE THREAD

**Issue by kivagant-ba** [jenkinsci/ansicolor-plugin#149]
I run a script that has some primitive formatting. After executing the script, the entire next output becomes bold (but not green). It doesn't happen in a normal terminal. How to completely reset all formatting after some commands?

### Test environment

- Jenkins Version: 2.150.2
- AnsiColor Version: 0.6.1
- Hostsystem: Ubuntu 16.04.4 LTS

### Expected behavior

After closing `ansiColor('xterm') { ... }` all further formatting should be reset to normal.

### Actual behavior

Everything is bold after ansiColor is finished its work.

![image](https://user-images.githubusercontent.com/44621442/51743648-0611ca80-20a6-11e9-851b-58adb56dcd4e.png)

### Steps to reproduce the behavior

```
pipeline {
    agent { label 'worker' }
    stages {
        stage('colors') {
            steps {
                script {
                    ansiColor('xterm') {
                        writeFile file: 'script.sh', text: '''#!/usr/bin/env bash

RED="\\e[31m"
GREEN="\\e[32m"
BOLD="\\e[1m"
NORMAL="\\e[0m"

printf "${GREEN}${BOLD}"
printf "All updated ...\\n"
printf "${NORMAL}"
'''
                        sh '''
cat script.sh && chmod +x script.sh
'''
                        sh './script.sh'
                    }
                    println 'Why am I so bold?'
                }
            }
        }
    }
}
```

**UP:** The same happens if the plugin used inside `options` section.
```
options {
        ansiColor('xterm')
    }
```

**Comment by dwnusbaum** [comment]
I think this is somewhat a dupe of #135 and should be fixed in 0.6.2 assuming your colorized script does output `sgr0` to reset the graphics mode before it returns.

Note though that as of 0.6.0, using the `ansicolor` step results in coloration of the entire log, not just the enclosed section, see: https://github.com/jenkinsci/ansicolor-plugin/blob/ff2264aa5d96ab819f96b904fec1766d529d194b/src/main/java/hudson/plugins/ansicolor/AnsiColorStep.java#L76

I am not sure if this is a regression from 0.5.x, but could be worth investigating.

**Comment by kivagant-ba** [comment]
> assuming your colorized script does output `sgr0` to reset the graphics mode before it returns.

I'm not sure if `\\e[0m` equal to `sgr0`, but in other terminals it works normally.

**Comment by dwnusbaum** [comment]
Yes `\\e[0m`/`\0o33[0m`/`\0x1b[0m` are all sgr0 (**s**et **g**raphics **r**endition 0), which resets the graphics mode.

**Comment by dwnusbaum** [comment]
Are you able to confirm whether this is working for you in 0.6.2?

**Comment by kivagant-ba** [comment]
@dwnusbaum , it's better, the code from the issue description works fine. But I still see some issues:

![image](https://user-images.githubusercontent.com/44621442/52952692-0c862000-338e-11e9-9bac-5213bfd7d73e.png)

The code from the script looks like this:

```bash
#!/usr/bin/env bash

GREEN="\e[32m"
BOLD="\e[1m"
NORMAL="\e[0m"

printf "${GREEN}${BOLD}All updated cookbooks have also updated their metadata versions.\n${NORMAL}" # this is the last line in the script, but everything below in the Jenkins console output is green 

```

**Comment by dwnusbaum** [comment]
@kivagant-ba Running ansicolor 0.6.2, I cannot reproduce that issue. Here is the Pipeline I am running:

```
ansiColor("xterm") {
    echo "\033[32m\033[1mColored-raw-echo.\n\033[0m"
}
echo "Uncolored-raw-echo"

node{
    ansiColor("xterm") {
        sh('''echo "\033[32m\033[1mColored-script-echo.\n\033[0m"''')
    }
    sh('''echo "Uncolored-script-echo"''')
}
```

And here is what it looks like:

<img width="275" alt="screen shot 2019-02-19 at 14 09 29" src="https://user-images.githubusercontent.com/1068968/53041017-e07fa300-3450-11e9-9f85-508faa6dd3bf.png">

What versions of Ansicolor and core Pipeline plugins (in particular Pipeline Job and Pipeline Nodes and Processes) are you running?

**Comment by kivagant-ba** [comment]
- Jenkins ver. 2.150.2
- Build Pipeline Plugin 1.5.8
- AnsiColorAdds ANSI coloring to the Console Output 0.6.2

```

pipeline {
    agent { label 'master' }
    stages {
        stage('colors') {
            steps {
                script {
                    ansiColor('xterm') {
                            writeFile file: 'script.sh', text: '''#!/usr/bin/env bash
    
GREEN="\\e[32m"
BOLD="\\e[1m"
NORMAL="\\e[0m"

printf "${GREEN}${BOLD}A line without resetting symbols."
'''
                            sh '''
cat script.sh && chmod +x script.sh
'''
                            sh './script.sh'
                        }

                    println 'Why am I so green and bold? Because the previous line doesn't have sgr0 at the end.'
                }
            }
        }
    }
}
```

**Comment by dwnusbaum** [comment]
> printf "${GREEN}${BOLD}A line without resetting symbols."

> The thing is that in the real script, the sgr0 exists at the end, but all logs are green.

Your example does not have sgr0 at the end. Do you have a simple reproduction case that does end with sgr0? If you do have such a reproduction, then I think it is a bug and would like to fix it.

I have only been able to reproduce the problem by leaving out sgr0, which I think can be considered a problem with the script creating the colorized text since it would apply to any system running the script and handling the ANSI escape sequences, not just Jenkins, and given that the `ansicolor` step covers the whole build, I am not sure of any obvious ways to _fix_ it. (We could work around it by writing out sgr0 to the logs when the block closes, but maybe some users were relying on the previous behavior and that seems a bit messy.)

**Comment by kivagant-ba** [comment]
I can't completely agree that this can be considered only as a script problem. Because the problem appears with third-party scripts, like chef-solo, for example, which users can't control. As a user I expect that the closing `}` should remove all formatting produced by AnsiColor plugin.

> The thing is that in the real script, the sgr0 exists at the end, but all logs are green.

And this is also true, but I can't show the full script here and it can't be reproduced when I'm testing against only the last message from the script.

**Comment by dwnusbaum** [comment]
>  Because the problem appears with third-party scripts, like chef-solo, for example, which users can't control

But if the problem is that chef-solo isn't closing its formatting on completion, then using chef-solo in the terminal means that all subsequent terminal output would be colored, right? In that case that seems like a bug in chef-solo and I would report it to them.

> As a user I expect that the closing } should remove all formatting produced by AnsiColor plugin

Yes, this is confusing, but I am not sure what we could do to fix it with the current implementation other than maybe writing out sgr0 at the end of the block, and I am not sure how well that would work. It would be clearer if the Pipeline `ansiColor` step was just a job property, because that more accurately reflects how it works.

> it can't be reproduced when I'm testing against only the last message from the script.

If you do figure out how to reproduce the issue I would be very curious to see what is happening.

**Comment by kivagant-ba** [comment]
>  then using chef-solo in the terminal means that all subsequent terminal output would be colored, right
No, locally it works fine. Only in Jenkins everything is colored after some of receipts executed on ec2 instances using chef-solo. I don't know when and why it happens.

**Comment by kivagant-ba** [comment]
Ok, let's close this. If someone find the same problem and can isolate it, maybe he will reopen this or create a new ticket.

Thank you!
